name: JumpGame
options:
  bundleIdPrefix: com.laplc
  deploymentTarget:
    iOS: 17.0
targets:
  JumpGame:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIInterfaceOrientation: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        PRODUCT_BUNDLE_IDENTIFIER: com.laplc.JumpGame
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
